version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: wavepulse
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build:
      context: ../api-service
      dockerfile: ../docker/api.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:1234@db:5432/wavepulse
    command: >
      bash -c "npx sequelize-cli db:migrate && npm start"

volumes:
  db-data: